name: GenAI Evaluation Pipeline

on:
  push:
    paths:
      - '**.py'
      - 'prompts/**'
      - 'config/**'
  workflow_dispatch:

jobs:
  run-evals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GenAI Evaluation
        run: python test_example.py

      - name: Upload Results CSV
        uses: actions/upload-artifact@v4
        with:
          name: eval-results
          path: results.csv
